controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

Activite_add:
    path: '/activite/add'
    controller: 'App\Controller\ActiviteController::addActivite'

exercices_add:
    path: '/exercices/add'
    controller: 'App\Controller\ExercicesController::addexercices'